apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thumbor

resources:
  - thumbor-backendconfig.yaml
  - thumbor-deployment.yaml
  - thumbor-ingress.yaml
  - thumbor-service.yaml
